# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "236e532e828e3c9853c7e207279c37eb"
name = "checkout-deploy-1"
handle = "checkout-deploy-1"
application_url = "https://renaissance-assign-argument-compatibility.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://renaissance-assign-argument-compatibility.trycloudflare.com/auth/callback",
  "https://renaissance-assign-argument-compatibility.trycloudflare.com/auth/shopify/callback",
  "https://renaissance-assign-argument-compatibility.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
