# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
name = "Line Item Message"
handle = "line-item-message"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
target = "purchase.checkout.cart-line-item.render-after"
module = "./src/Checkout.jsx"  
export = "purchaseCheckoutCartLineItemRenderAfter"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]   
# namespace = "my_namespace"
# key = "my_other_key"

[[extensions.metafields]]
    namespace = "billing"
    key = "active_plan"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
    [[extensions.settings.fields]]
    key = "message_text"
    type = "single_line_text_field"
    name = "Message Text"
    description = "Add Message text use"

    [[extensions.settings.fields]]
    key = "text_tone"
    type = "single_line_text_field"
    name = "Text  Tone"
    description = "Changes the visual appearance"
        [[extensions.settings.fields.validations]]
        name = "choices"
        value = "[\"none\", \"accent\", \"subdued\", \"info\", \"success\", \"warning\", \"critical\"]"
