api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "hide-shipping-method"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.delivery-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
